services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  postgresDb:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  neo4jDb:
    image: neo4j:latest
    env_file:
      - .env
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
    driver: local
  neo4j_data:
    driver: local
